/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WorkbenchRouteRouteImport } from './routes/workbench/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkbenchIndexRouteImport } from './routes/workbench/index'
import { Route as WorkbenchTokensRouteImport } from './routes/workbench/tokens'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRouteRoute = WorkbenchRouteRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIndexRoute = WorkbenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchRouteRoute,
} as any)
const WorkbenchTokensRoute = WorkbenchTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => WorkbenchRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workbench': typeof WorkbenchRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/workbench/tokens': typeof WorkbenchTokensRoute
  '/workbench/': typeof WorkbenchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/workbench/tokens': typeof WorkbenchTokensRoute
  '/workbench': typeof WorkbenchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workbench': typeof WorkbenchRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/workbench/tokens': typeof WorkbenchTokensRoute
  '/workbench/': typeof WorkbenchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workbench' | '/about' | '/workbench/tokens' | '/workbench/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/workbench/tokens' | '/workbench'
  id:
    | '__root__'
    | '/'
    | '/workbench'
    | '/about'
    | '/workbench/tokens'
    | '/workbench/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkbenchRouteRoute: typeof WorkbenchRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench/': {
      id: '/workbench/'
      path: '/'
      fullPath: '/workbench/'
      preLoaderRoute: typeof WorkbenchIndexRouteImport
      parentRoute: typeof WorkbenchRouteRoute
    }
    '/workbench/tokens': {
      id: '/workbench/tokens'
      path: '/tokens'
      fullPath: '/workbench/tokens'
      preLoaderRoute: typeof WorkbenchTokensRouteImport
      parentRoute: typeof WorkbenchRouteRoute
    }
  }
}

interface WorkbenchRouteRouteChildren {
  WorkbenchTokensRoute: typeof WorkbenchTokensRoute
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
}

const WorkbenchRouteRouteChildren: WorkbenchRouteRouteChildren = {
  WorkbenchTokensRoute: WorkbenchTokensRoute,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
}

const WorkbenchRouteRouteWithChildren = WorkbenchRouteRoute._addFileChildren(
  WorkbenchRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkbenchRouteRoute: WorkbenchRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
